import type { NextPage } from 'next'
import { useState } from "react"
import Head from 'next/head'

const Home: NextPage = () => {
	const [value, setValue] = useState<number>(0)
  return (
    <div>
      <Head>
        <title>W Movie</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>

      </main>
    </div>
  )
}

export default Home
